# Generated by Django 5.1.3 on 2025-11-28 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_title', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-record_text__date'],
            },
        ),
        migrations.CreateModel(
            name='RecordText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('assigned_doctor', models.CharField(max_length=255)),
                ('admitted_at', models.DateTimeField()),
                ('ward', models.CharField(help_text='Example: Ward A - Room 204', max_length=255)),
                ('status', models.CharField(choices=[('pre_op', 'Pre-OP'), ('in_surgery', 'In Surgery'), ('in_recovery', 'In Recovery'), ('discharged', 'Discharged'), ('critical', 'Critical'), ('stable', 'Stable')], default='pre_op', max_length=20)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
