# Generated by Django 5.1.3 on 2025-11-28 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_email_alter_patient_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_plan', models.JSONField(blank=True, default=dict)),
                ('diet_plan', models.JSONField(blank=True, default=dict)),
                ('activities', models.JSONField(blank=True, default=dict)),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_summary', to='patients.patient')),
            ],
        ),
    ]
