# Generated by Django 5.1.3 on 2025-11-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patientcareplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcareplan',
            name='today_tasks',
            field=models.JSONField(blank=True, default=list, help_text="List of today's tasks with completion status"),
        ),
    ]
