# Generated by Django 5.1.3 on 2025-11-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patientcareplan_today_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('in_recovery', 'In Recovery'), ('discharged', 'Discharged')], default='in_recovery', max_length=20),
        ),
    ]
