# Generated by Django 5.1.3 on 2025-11-29 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_add_task_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='ward',
        ),
    ]
