# Generated by Django 5.1.3 on 2025-11-28 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        ('surgeries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityplan',
            name='allowed',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='restricted',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='allowed_foods',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='forbidden_foods',
        ),
        migrations.AddField(
            model_name='activityplan',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='protein_target',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='surgery',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='hospitals.hospital'),
        ),
        migrations.CreateModel(
            name='ActivityPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('allowed', 'Allowed'), ('restricted', 'Restricted')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='surgeries.activityplan')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DietPlanFoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('allowed', 'Allowed'), ('forbidden', 'Forbidden')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='surgeries.dietplan')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DietPlanMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('time', models.CharField(blank=True, max_length=50)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='surgeries.dietplan')),
            ],
            options={
                'ordering': ['meal_type', 'time'],
            },
        ),
    ]
