# Generated by Django 5.1.3 on 2025-11-28 19:39

import django.db.models.deletion
from django.db import migrations, models


def migrate_type_data(apps, schema_editor):
    """Create SurgeryType records from existing type strings and link them."""
    Surgery = apps.get_model('surgeries', 'Surgery')
    SurgeryType = apps.get_model('surgeries', 'SurgeryType')
    
    # Get all unique type values from existing surgeries
    type_values = Surgery.objects.values_list('type', flat=True).distinct()
    
    # Create SurgeryType records for each unique type
    type_map = {}
    for type_value in type_values:
        if type_value:  # Skip None/empty values
            surgery_type, created = SurgeryType.objects.get_or_create(
                name=type_value,
                defaults={'description': ''}
            )
            type_map[type_value] = surgery_type.id
    
    # Update all surgeries to link to the appropriate SurgeryType
    for surgery in Surgery.objects.all():
        if surgery.type and surgery.type in type_map:
            surgery.type_id = type_map[surgery.type]
            surgery.save(update_fields=['type_id'])


def reverse_migrate_type_data(apps, schema_editor):
    """Reverse migration: convert ForeignKey back to CharField."""
    Surgery = apps.get_model('surgeries', 'Surgery')
    SurgeryType = apps.get_model('surgeries', 'SurgeryType')
    
    # Convert ForeignKey IDs back to type names
    for surgery in Surgery.objects.all():
        if surgery.type_id:
            try:
                surgery_type = SurgeryType.objects.get(id=surgery.type_id)
                surgery.type = surgery_type.name
                surgery.save(update_fields=['type'])
            except SurgeryType.DoesNotExist:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('surgeries', '0002_remove_activityplan_allowed_and_more'),
    ]

    operations = [
        # Step 1: Create SurgeryType model
        migrations.CreateModel(
            name='SurgeryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Surgery Type',
                'verbose_name_plural': 'Surgery Types',
                'ordering': ['name'],
            },
        ),
        # Step 2: Rename risk_level to priority_level
        migrations.RenameField(
            model_name='surgery',
            old_name='risk_level',
            new_name='priority_level',
        ),
        # Step 3: Add temporary integer field for ForeignKey
        migrations.AddField(
            model_name='surgery',
            name='type_id',
            field=models.IntegerField(null=True, blank=True),
        ),
        # Step 4: Migrate data - create SurgeryType records and populate type_id
        migrations.RunPython(migrate_type_data, reverse_migrate_type_data),
        # Step 5: Remove old type CharField
        migrations.RemoveField(
            model_name='surgery',
            name='type',
        ),
        # Step 6: Rename type_id to type and convert to ForeignKey
        migrations.RenameField(
            model_name='surgery',
            old_name='type_id',
            new_name='type',
        ),
        # Step 7: Alter the field to be a proper ForeignKey
        migrations.AlterField(
            model_name='surgery',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries', to='surgeries.surgerytype'),
        ),
    ]
