# Generated by Django 5.1.3 on 2025-11-28 20:00

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def set_default_dates(apps, schema_editor):
    """Set default dates for existing activity plans."""
    ActivityPlan = apps.get_model('surgeries', 'ActivityPlan')
    now = timezone.now()
    ActivityPlan.objects.all().update(created_at=now, updated_at=now)


class Migration(migrations.Migration):

    dependencies = [
        ('surgeries', '0004_add_hospital_to_diet_plan'),
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityplan',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_plans', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='activityplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activityplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_dates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='activityplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activityplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
