# Generated by Django 5.1.3 on 2025-11-28 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surgeries', '0005_add_hospital_to_activity_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Activity plan', 'verbose_name_plural': 'Activity plans'},
        ),
        migrations.AlterModelOptions(
            name='dietplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Diet plan', 'verbose_name_plural': 'Diet plans'},
        ),
    ]
