# Generated by Django 5.1.3 on 2025-11-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surgeries', '0006_alter_activityplan_options_alter_dietplan_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='patient',
        ),
    ]
